inventory_list/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import register, login_user, logout_user, get_product_json, add_product_ajax, count_product_json, delete_product_ajax, create_product_flutter

app_name = 'main'

urlpatterns = [
    # access the imported function that located in views
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    # access the previously imported json function in views
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('count-product/', count_product_json, name='count_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('delete-product-ajax/<int:id>',
         delete_product_ajax, name='delete_product_ajax'),
    path('create-flutter/', create_product_flutter,
         name='create_product_flutter'),


]

main/models.py
from django.db import models
from django.contrib.auth.models import User


class Item(models.Model):
    name = models.CharField(max_length=255)
    date_added = models.DateField(auto_now_add=True)
    amount = models.IntegerField()
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_discount = models.BooleanField(default=False)

main/forms.py
from django.forms import ModelForm
from main.models import Item


class ProductForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "description"]

main/views.py
from django.http import JsonResponse
from .models import Item
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from main.forms import ProductForm
from main.models import Item
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.views.decorators.csrf import csrf_exempt
import json


@login_required(login_url='/login')
def show_main(request):
    items = Item.objects.filter(user=request.user)
    count = Item.objects.filter(user=request.user).count()
    # products = Product.objects.filter(user=request.user)

    context = {
        'app_name': 'Inventory Management',
        # 'name': 'Tiva Adhisti Nafira Putri',
        'name': request.user.username,
        'class': 'PBP KI',
        'items': items,
        'items_count': count,
        'last_login': request.COOKIES['last_login'],

    }

    return render(request, "main.html", context)


def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form': form}
    return render(request, 'register.html', context)

# login function to authenticate a user


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(
                request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response


def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")


def show_json(request):
    data = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

# Retrieving Data Based on ID in XML and JSON Formats


def show_xml_by_id(request, id):
    # store the query result of data with a specific ID from the Product model
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")


def show_json_by_id(request, id):
    # store the query result of data with a specific ID from the Product model
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


def get_product_json(request):
    product_item = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))


def count_product_json(request):
    count = Item.objects.filter(user=request.user).count()
    return HttpResponse(serializers.serialize('json', count))


def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user
        is_discount = request.POST.get("is_discount")
        if is_discount == None:
            is_discount = False

        new_product = Item(name=name, amount=amount,
                           description=description, user=user, is_discount=is_discount)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()


@csrf_exempt
def delete_product_ajax(request, id):
    item = Item.objects.get(pk=id)
    item.delete()
    return HttpResponse(b"DELETED", status=201)


@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)

        new_product = Item.objects.create(
            user=request.user,
            name=data["name"],
            amount=int(data["amount"]),
            description=data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

    from django.contrib.auth.decorators import login_required

main/templates/create_product.html
{% extends 'base.html' %}

{% block content %}

<head>
    <style>
        .card {
            background-color: white;

            /* text-align: center; */
            display: flex;
            justify-content: center;
            border: none;

            padding: 20px;
            box-shadow: 0px 16px 40px 0px rgba(255, 255, 255, 0.42) !important;
            background-color: #fdfeff6f;
            -webkit-backdrop-filter: blur(15px);
            backdrop-filter: blur(15px);
            border-radius: 20px;
        }

        h1 {
            color: white;
            font-family: Arial, Helvetica, sans-serif;
            padding: 10px;
            font-size: 30px;
        }

        label {
            font-family: Arial, Helvetica, sans-serif;
        }

        .header {
            position: fixed;
            width: 100%;
            padding: 10px 25px;
            /* background-color: blue; */
            display: flex;
            justify-content: space-between;
            align-items: center;
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
            color: white;
            background-color: rgb(31, 45, 112);
        }

        .add-card {
            background: linear-gradient(90deg, rgba(19, 39, 130, 1) 0%, rgba(53, 63, 126, 1) 41%, rgba(91, 112, 185, 1) 100%);
            width: 300px;
            text-align: center;
            border-radius: 5px;
            margin-left: 10px;


        }
    </style>
</head>

<div
    style="background-image: url('https://img.freepik.com/free-vector/white-abstract-background_23-2148818118.jpg'); height: 100vh; background-repeat: no-repeat; background-attachment: fixed; background-size: cover;">
    <div class="position-absolute top-50 start-50 translate-middle">
        <div class="card">
            <div class="card-body" style="padding-top: 50px; padding-bottom: 50px;">
                <h1 style="color: black;">
                    Add New Product
                </h1>
                <form method="POST" style="margin-left: 10px;">
                    {% csrf_token %}
                    <table>
                        {{ form.as_table }}
                        <tr>
                            <td></td>
                            <td>

                                <input type="submit" value="Add Product" />
                            </td>

                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </div>
    <div class="container-fluid " style="padding: 0px;">
        <div class="row content">
            <div class="col-sm-2 sidenav hidden-xs" style="height: 100vh;">


            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}


<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        .card {
            background-color: white;

            /* text-align: center; */
            display: flex;
            justify-content: center;
            border: none;

            padding: 20px;
            box-shadow: 0px 16px 40px 0px rgba(255, 255, 255, 0.42) !important;
            background-color: #fdfeff6f;
            -webkit-backdrop-filter: blur(15px);
            backdrop-filter: blur(15px);
            height: 80%;
            width: 80%;
            border-radius: 20px;
        }

        .header {
            position: fixed;
            width: 100%;
            padding: 10px 25px;
            /* background-color: blue; */
            display: flex;
            justify-content: space-between;
            align-items: center;
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
            color: white;
        }

        /* .btn-login-popup {
            background-color: transparent;
            border: 2px solid white !important;
            border-radius: 6px !important;
            cursor: pointer;
            font-weight: 500;
            padding: 4px 25px;
            font-size: 17px;
            color: white;
        } */
        .button {
            background-color: rgb(42, 61, 155);
        }

        .btn-login-popup:hover {
            background-color: rgba(255, 255, 255, 0.679);
        }
    </style>
</head>


<div
    style="background-image: url('https://w0.peakpx.com/wallpaper/33/306/HD-wallpaper-2019-ios-13-dark-mode-black-gradient-abstract.jpg'); height: 100vh; background-repeat: no-repeat; background-attachment: fixed; background-size: cover;">
    <!-- <nav class="navbar bg-body-tertiary" style="background-color: red;">
        <div class="container-fluid">
            <a class="navbar-brand">InVentory</a>
            <form class="d-flex" role="search">
                <button class="btn btn-outline-success me-2" type="button">Sign In</button>
            </form>
        </div>
    </nav> -->

    <header class="header">
        <h2 class="logo">InVentory</h2>
        <!-- <button class="btn-login-popup" type="button">Sign In</button> -->
    </header>




    <div class="position-absolute top-50 start-50 translate-middle">
        <div class="card" style="width: 400px; height: 400px;">
            <div class="card-body" style="padding-top: 50px; padding-bottom: 50px;">
                <div class="login">

                    <h1 style="text-align: center;">Sign In</h1>

                    <form method="POST" action="">
                        {% csrf_token %}
                        <table>
                            <div class="mb-3">
                                <label for="exampleFormControlInput1" class="form-label">Email address</label>
                                <input type="text" class="form-control" name="username" placeholder="username">
                            </div>

                            <label for="inputPassword5" class="form-label">Password</label>
                            <input type="password" name="password" class="form-control">
                            <br>
                            <div class="d-grid gap-2">
                                <button style="background: rgb(12, 14, 25);; border: rgb(11, 15, 33);"
                                    class="btn btn-primary" type="submit" value="Login">Sign In</button>
                            </div>
                            <br>
                        </table>
                    </form>


                    {% if messages %}
                    <ul>
                        {% for message in messages %}
                        <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}

                    Don't have an account yet? <a style="color: rgb(49, 92, 141);"
                        href="{% url 'main:register' %}">Register Now</a>

                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}


<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td,
        th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;

        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }

        .logout-btn {
            border-radius: 5px;
            background-color: transparent;
            border: #3463ad;
            color: white;
            display: flex;
            margin: auto;
            justify-content: center;
            align-items: center;
            padding: 5px 10px;
            cursor: pointer;
            font-size: 20px;

        }

        .new-btn {
            border-radius: 5px;
            background-color: #3463ad;
            border: #3463ad;
            color: white;
            display: flex;
            margin: auto;
            justify-content: center;
            align-items: center;
            padding: 5px 10px;
            cursor: pointer;
            font-size: 15px;
            margin-top: 20px;
        }

        .new-btn:hover {
            background-color: #3b70c4;
            border: #3b70c4;
            cursor: pointer;
        }

        .delete-btn {
            border-radius: 5px;
            /* background-color: red;
            border: red; */
            color: rgb(0, 0, 0);
            display: flex;
            margin: auto;
            justify-content: center;
            align-items: center;
            padding: 5px 10px;
            cursor: pointer;
            font-size: 15px;
            background-color: #fdfeff6f;
            -webkit-backdrop-filter: blur(15px);
            backdrop-filter: blur(15px);
        }

        a {
            text-decoration: none;
        }

        .header {
            position: fixed;
            width: 100%;
            padding: 10px 25px;
            /* background-color: blue; */
            display: flex;
            justify-content: space-between;
            align-items: center;
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
            color: white;
            background-color: rgb(31, 45, 112);
        }

        .logout-btn:hover {
            color: #e4e8ee;
        }

        .card-name {
            width: 250px;
            height: 30px;
            border-radius: 10px;
            display: flex;
            justify-content: center;
            align-items: center;
            align-content: center;
            padding-top: 10px;
            border: 2px solid black;
            margin-left: 10px;
            margin-bottom: 10px;

        }

        .card-table {
            background-color: white;
            border-radius: 10px;
            box-shadow: 10px 16px 40px 10px rgba(112, 144, 176, 0.20);
            padding: 20px;
            margin: 20px;

        }

        .side-nav {
            width: 250px;
            height: 100%;
            position: fixed;
            top: 0;
            left: 0;
            padding: 30px 15px;
            background-color: white;
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
            font-size: 20px;

        }

        .side-item {
            padding: 10px;
        }

        .side-item:hover {
            background: #3463ad;
            padding: 10px;
            border-radius: 10px;
            color: white;
        }

        a {
            text-decoration: none;
            color: black;
            font-size: 20px;

        }

        a:hover {
            color: #3463ad;
        }

        .card-item {
            background-color: #b4d2ff;
            color: rgb(38, 111, 213);
            padding: 20px;
            width: 370px;
            border-radius: 10px;
            box-shadow: 0px 16px 15px 0px rgba(112, 144, 176, 0.20);
            margin: 20px;

        }
    </style>
</head>



<div class="container-fluid " style="padding: 0px;">
    <div class="row content">
        <div class="col-sm-2 sidenav hidden-xs" style="height: 100vh;">
            <h2 style="text-align: center; padding-top: 20px; font-size: 40px;">InVentory</h2>
            <hr style="margin-left: 15px;">
            <br>
            <div style="margin-left: 20px;">
                <img width="20px" style="padding-bottom: 5px;"
                    src="https://cdn-icons-png.flaticon.com/128/3757/3757985.png">
                <a style=" padding-left: 10px; " href="/">Dashboard</a></li>
            </div>
            <br>
            <div style="margin-left: 20px;">
                <img width="20px" style="padding-bottom: 5px; position: fixed; bottom: 30px; left: 30px;"
                    src="https://cdn-icons-png.flaticon.com/128/2099/2099238.png">
                <a style="position: fixed; bottom: 30px; padding-left: 40px;" href="{% url 'main:logout' %}">
                    Logout

                </a>
            </div>
        </div>
        <br>

        <div class="col-sm-10" style="background: #f3f4f4; height: 100vh;">
            <div class="well">

                <h5 style="font-size: 25px; margin-bottom: 10px; font-weight: 600; margin: 20px;">
                    Welcome Back, {{name}}!
                </h5>

                <div class="card-item" id="item-count">
                    <b id="item-count"
                        style="color: rgb(38, 111, 213); font-family:system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; padding: 0px; margin: 0px;">
                        You have saved {{items_count}} items in this
                        application</b>
                </div>
                <!-- <h5 style="margin-top: 0px; text-align: center;">
                    {{class}}
                </h5> -->

                <!DOCTYPE html>
                <html>
                <div class="card-table">
                    <table id="product_table"></table>
                </div>
                <!-- <div class="card-table">

                    <table>
                        <tr>
                            <th>Name</th>
                            <th>Amount</th>
                            <th>Description</th>
                            <th> Date Added</th>
                        </tr>

                        {% comment %} Below is how to show the product data {% endcomment %}

                        {% for item in items %}
                        <tr>
                            <td>{{item.name}}</td>
                            <td>{{item.amount}}</td>
                            <td>{{item.description}}</td>
                            <td>{{item.date_added}}</td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div> -->

                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <form id="form" onsubmit="return false;">
                                    {% csrf_token %}
                                    <div class="mb-3">
                                        <label for="name" class="col-form-label">Name:</label>
                                        <input type="text" class="form-control" id="name" name="name"></input>
                                    </div>
                                    <div class="mb-3">
                                        <label for="amount" class="col-form-label">Amount:</label>
                                        <input type="number" class="form-control" id="amount" name="amount"></input>
                                    </div>
                                    <div class="mb-3">
                                        <label for="description" class="col-form-label">Description:</label>
                                        <textarea class="form-control" id="description" name="description"></textarea>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" value="1" name="is_discount">
                                        <label class="form-check-label" for="flexCheckDefault">
                                            Discount
                                        </label>
                                    </div>
                                </form>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <button type="button" class="btn btn-primary" id="button_add"
                                    data-bs-dismiss="modal">Add
                                    Item</button>
                            </div>
                        </div>
                    </div>
                </div>


                <button type="button" class="new-btn" data-bs-toggle="modal" data-bs-target="#exampleModal">Add
                    New Item</button>
                <!-- <div>
                    <a href="{% url 'main:create_product' %}">
                        <button class="new-btn">
                            Add New Product
                        </button>
                    </a>
                </div> -->

                <h5 style="padding-left: 15px; font-size: 15px; margin: 20px;">Last login session: {{ last_login }}</h5>

            </div>
        </div>
    </div>

    <script>
        async function getProducts() {
            return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
        }


        async function refreshProducts() {

            document.getElementById("product_table").innerHTML = ""
            const products = await getProducts()
            let htmlString =
                `<tr>
            <th>Name</th>
            <th>Amount</th>
            <th>Description</th>
            <th>Date Added</th>
            <th>Discount</th>
            <th>Action</th>
        </tr>`
            products.forEach((item) => {
                htmlString = htmlString + `\n`;
                if (item.fields.is_discount) {
                    htmlString += `<tr style = "background-color:red">`;
                } else {
                    htmlString += `<tr style = "background-color:blue">`;
                }

                htmlString +=
                    `<td>${item.fields.name}</td>
                    <td>${item.fields.amount}</td>
                    <td>${item.fields.description}</td>
                    <td>${item.fields.date_added}</td>
                    <td>${item.fields.is_discount}</td>
                    <td>
                        <button class="delete-btn" onclick="deleteProduct(${item.pk})">
                            Delete
                        </button>
                    </td>

                </tr>`
            })

            document.getElementById("product_table").innerHTML = htmlString
        }

        refreshProducts()

        function addProduct() {
            fetch("{% url 'main:add_product_ajax' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(refreshProducts)

            document.getElementById("form").reset()
            return false
        }

        document.getElementById("button_add").onclick = addProduct

        function deleteProduct(id) {
            fetch("delete-product-ajax/" + id, {
                method: "POST"
            }).then(refreshProducts)

            document.getElementById("form").reset()
            return false
        }

    </script>

    {% endblock content %}

main/templates/navbar.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar bg-body-tertiary fixed-top">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar"
            aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#">Offcanvas navbar</a>
        <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar"
            aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Offcanvas</h5>
                <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Dropdown
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="d-flex mt-3" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </div>
</nav>
{% endblock content %}